language: python
python:
  - 3.5
install:
  - pip3 install tensorflow
script:
  - python mnist.py
aftersuccess:
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB
    on:
      branch: master
